- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt: name={{item}}
    with_items:
      - htop
      - mc
      - screen
      - tmux
      - ansible
      - ansible-lint
      - xdotool
      - wireguard
      - wget
      - httpie
      - vlc
      - vim
      - solaar
      - thunderbird
      - chromium
      
